mongo:
  uri: mongodb://127.0.0.1:27017
  db-name: antivirus

magic-numbers:
  zip:
    - byte-string: 50 4B 03 04
      offset: 0
    - byte-string: 50 4B 05 06
      offset: 0
    - byte-string: 50 4B 07 08
      offset: 0
  executable:
    - byte-string: CF FA ED FE
      offset: 0

temp-dir-cleaner:
    ttl: 30
    delay: 30
